### ISSUE TITLE
Error bei Installation in einer frischen Contao 4.4.19 Umgebung

### ISSUE THREAD

**Issue by chriza** [heimrichhannot/contao-isotope-bundle#2]
Hallo,

irgendwas scheine ich falsch zu machen. 

Sowohl bei C4.5.9, als auch bei C4.4.19 erhalte ich folgenden Composer-Fehler:

Package heimrichhannot/contao-request is abandoned, you should avoid using it. Use heimrichhannot/contao-request-bundle instead.
Package heimrichhannot/contao-ajax is abandoned, you should avoid using it. Use heimrichhannot/contao-ajax-bundle instead.
Package heimrichhannot/contao-multi_column_editor is abandoned, you should avoid using it. Use heimrichhannot/contao-multi-column-editor-bundle instead.
Package heimrichhannot/contao-be_explanation is abandoned, you should avoid using it. Use heimrichhannot/contao-be_explanation-bundle instead.
Package heimrichhannot/contao-multifileupload is abandoned, you should avoid using it. Use heimrichhannot/contao-multifileupload-bundle instead.
Writing lock file
Generating autoload files
Warning: Ambiguous class resolution, "Contao\Versions" was found in both "/www/htdocs/w0555fb8/webpages/contao44/vendor/heimrichhannot/contao-versions/src/Resources/contao/classes/Versions.php" and "/www/htdocs/w0555fb8/webpages/contao44/vendor/contao/core-bundle/src/Resources/contao/classes/Versions.php", the first will be used.
> ComponentInstaller\Installer::postAutoloadDump
Compiling component files
> Contao\ManagerBundle\Composer\ScriptHandler::initializeApplication

 Added/updated the web/app_dev.php file.
 Added/updated the web/app.php file.

 // Clearing the cache for the prod environment with debug
 // false

 [OK] Cache for the "prod" environment (debug=false) was successfully cleared.

 // Warming up the cache for the prod environment with debug
 // false

22:14:39 ERROR     [console] Error thrown while running command "--ansi cache:warmup --env=prod". Message: "(Sub)palette "slick_eventlist" not found in table "tl_module"" ["exception" => InvalidArgumentException { …},"command" => "--ansi cache:warmup --env=prod","message" => "(Sub)palette "slick_eventlist" not found in table "tl_module""] []

In PaletteManipulator.php line 211:

  (Sub)palette "slick_eventlist" not found in table "tl_module"

cache:warmup [--no-optional-warmers] [-h|--help] [-q|--quiet] [-v|vv|vvv|--verbose] [-V|--version] [--ansi] [--no-ansi] [-n|--no-interaction] [-e|--env ENV] [--no-debug] [--] <command>

Script Contao\ManagerBundle\Composer\ScriptHandler::initializeApplication handling the post-update-cmd event terminated with an exception

  [RuntimeException]
  An error occurred while executing the "cache:warmup" command: 22:14:39 ERROR     [console] Error thrown while running command "--ansi cache:warmup
   --env=prod". Message: "(Sub)palette "slick_eventlist" not found in table "tl_module"" ["exception" => Invali
  dArgumentException { …},"command" => "--ansi cache:warmup --env=prod","
  mmessage" => "(Sub)palette "slick_eventlist" not found in table "tl_module""] []

  In PaletteManipulator.php line 211:

    (Sub)palette "slick_eventlist" not found in table "tl_module"

  cache:warmup [--no-optional-warmers] [-h|--help] [-q|--quiet] [-v|vv|vvv|--verbose] [-V|--version] [--ansi] [--no-ansi] [-n|--no-interaction] [-e|--env ENV] [--n
  o-debug] [--] <command>

update [--prefer-source] [--prefer-dist] [--dry-run] [--dev] [--no-dev] [--lock] [--no-custom-installers] [--no-autoloader] [--no-scripts] [--no-progress] [--no-suggest] [--with-dependencies] [--with-all-dependencies] [-v|vv|vvv|--verbose] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--apcu-autoloader] [--ignore-platform-reqs] [--prefer-stable] [--prefer-lowest] [-i|--interactive] [--root-reqs] [--] [<packages>]...

**Comment by fatcrobat** [comment]
Scheint am PaletteManipulator von Contao zu liegen. Wir selbst verwenden diesen nirgends. Hast du eine Erweiterung installiert, die darauf aufbaut?

**Comment by chriza** [comment]
Meine composer.json sieht normalerweise so aus:
    "require": {
        "php": "^5.6|^7.0",
        "contao/calendar-bundle": "^4.4",
        "contao/comments-bundle": "^4.4",
        "contao/faq-bundle": "^4.4",
        "contao/listing-bundle": "^4.4",
        "contao/manager-bundle": "4.4.*",
        "contao/news-bundle": "^4.4",
        "contao/newsletter-bundle": "^4.4",
        "agoat/contao-customcontentelements": "^2.3",
        "agoat/contao-deferredimages": "^1.3",
        "bugbuster/contao-mobiledetection-bundle": "^1.0",
        "christianbarkowsky/contao-tiny-compress-images": "^1.0",
        "christianbarkowsky/rel-canonical": "^3.3",
        "contao-bootstrap/bundle": "^2.0",
        "contao-community-alliance/merger2": "4.0.x-dev",
        "derhaeuptling/contao-mobilecontent": "^2.2",
        "isotope/isotope-core": "^2.5",
        "isotope/isotope_documents": "^1.0",
        "jrgregory/m17-sticky-backend-footer": "^2.0",
        "madeyourday/contao-rocksolid-custom-elements": "^2.1",
        "markocupic/bootstrap-carousel-bundle": "^1.0",
        "markocupic/rotate_image": "^1.0",
        "menatwork/contao-matomotrackingtag-bundle": "^1.0",
        "menatwork/semantic_html5": "^2.0",
        "numero2/contao-opengraph3": "^4.0",
        "oneup/contao-j2b": "^2.0",
        "pdir/social-feed-bundle": "^2.0",
        "terminal42/contao-inserttags": "^1.9",
        "terminal42/notification_center": "^1.4",
        "terminal42/contao-leads": "^1.4",
        "terminal42/contao-easy_themes": "^2.2",
        "terminal42/contao-mailusername": "^1.0",
        "pliigo/pagecacheenabler-bundle": "^1.1"
    },

Habe jetzt eine ganz frische Installation mit folgender compser.json erstellt:
    "require": {
        "php": "^7.1",
        "contao/calendar-bundle": "^4.5",
        "contao/comments-bundle": "^4.5",
        "contao/faq-bundle": "^4.5",
        "contao/listing-bundle": "^4.5",
        "contao/manager-bundle": "4.5.*",
        "contao/news-bundle": "^4.5",
        "contao/newsletter-bundle": "^4.5",
        "heimrichhannot/contao-isotope-bundle": "^0.11",
        "isotope/isotope-core": "^2.5",
        "isotope/isotope_documents": "^1.0"
    },
Da erhalte ich noch folgenden Fehler:

www/htdocs/w0145ccc8/webpages/contao-manager$ php71 composer update
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for heimrichhannot/contao-isotope-bundle ^0.11 -> satisfiable by heimrichhannot/contao-isotope-bundle[0.11.0].
    - heimrichhannot/contao-isotope-bundle 0.11.0 requires heimrichhannot/contao-slick-bundle ^1.0.0-beta -> satisfiable by heimrichhannot/contao-slick-bundle[1.0.0-beta, 1.0.0-beta2, 1.0.0-beta3, 1.0.0-beta4, 1.0.0-beta5] but these conflict with your requirements or minimum-stability.

**Comment by koertho** [comment]
In this case it should help add `"prefer-stable": true` to the composer.json.
