### ISSUE TITLE
The service "huh.isotope.listener.hooks" was not found or is not public

### ISSUE THREAD

**Issue by DrAColian** [heimrichhannot/contao-isotope-bundle#3]
Die im Titel genannte Fehlermeldung erscheint, wenn ich das Paket unter Conato 4.6 installiere. (Es wäre auch schön, wenn ihr die Abhängigkeiten der benötigten Pakete anpassen könntet. Symfony 3.4 wird für Contao 4.6 nicht mehr empfohlen, ~~aber u.a. vom slick-bundle benötigt~~ *[edit: hier gab es mittlerweile schon ein update - aber das isotope-bundle hat es ja leider auch in den required packages stehen]*!)

Als Lösung wird die Korrektur der services.yaml aufgeführt (siehe https://symfony.com/doc/current/service_container.html#public-versus-private-services )

**Comment by DrAColian** [comment]
Könntet ihr bitte in die Abhängigkeit noch das symfony-framework ab V4 mit reinnehmen? Das bundle lässt sich leider sonst immer noch nicht installieren.

**Comment by fritzmg** [comment]
@DrAColian you need to execute the following:
```
composer require heimrichhannot/contao-isotope-bundle --no-update && composer update
```
This will downgrade some of your symfony packages.

However, the bundle should not require `symfony/framework-bundle` in the first place: #4

**Comment by DrAColian** [comment]
@fritzmg I don't have console access to the server, so I can just use the manager. It worked, with some difficulties... I'll try it the next days...

The manager gave me the following message:

```
Package heimrichhannot/contao-teaser is abandoned, you should avoid using it. Use heimrichhannot/contao-teaser-bundle instead.
Package heimrichhannot/contao-be_explanation is abandoned, you should avoid using it. Use heimrichhannot/contao-be_explanation-bundle instead.
Package heimrichhannot/contao-request is abandoned, you should avoid using it. Use heimrichhannot/contao-request-bundle instead.
Package heimrichhannot/contao-ajax is abandoned, you should avoid using it. Use heimrichhannot/contao-ajax-bundle instead.
Package heimrichhannot/contao-inserttag_download is abandoned, you should avoid using it. Use heimrichhannot/contao-inserttagcollection-bundle instead.
```
Any chance for solving this one on my own?

**Comment by fritzmg** [comment]
Just add the package in the Contao Manager, select every package to be updated and then run a a package update.
